spring:
  application:
    name: SSAFYSecurities
  data:
    mongodb:
      uri: mongodb+srv://S11P23C203:jGhlp5h55N@ssafy.ngivl.mongodb.net/S11P23C203?authSource=admin
      # username: S11P22C203
      # password: jGhlp5h55N
      # host: MongoDB 서버 주소 (예: localhost)
      # port: MongoDB 포트 (기본값은 27017)
      # database_name: 접속할 데이터베이스 이름
#  datasource:
#    url: jdbc:postgresql://j11c203.p.ssafy.io:5432/postgres
#    username: postgres
#    password: ssafy
#  jpa:
#    hibernate:
#      dialect: org.hibernate.dialect.PostgreSQL10Dialect
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true

koreainvestment:
  PROD: https://openapi.koreainvestment.com:9443
  APPKEY: PSZCPitXw2BiWOMQeqz7RLBHZgv3gv9ngm1p
  APPSECRET: elbH3KH4gGgFU1QUABzRwKp2rQMDNdrQDNwfdFKijoF5a0YvO7LaonR4lB1hrEvbCBN/fWa2GVjWpofto9unuIMMvIJHjbiommdESV+B37x6KG+pFqfirzG9ptJz8Woa2kMeylYVWclhclUZ8kDgpOuxo0SeQaZZhnbTeYw+V0HJ8OpE6nw=
#  host: openapi.koreainvestment.com

stock:
   websocket:
     url: ws://ops.koreainvestment.com:21000
   codes: 005930,086520,000660,035420,373220,352820,035720,005380,001040,105560,000810,010130,000100,068270,006400,051910,000670,247540,096770,196170

upbit:
  PROD: https://api.upbit.com/v1
  WEBSOCKET:
    PROD: wss://api.upbit.com/websocket/v1
#  ACCESSKEY: QauB92cfsThPbex33yRgUltQKMyPs3IDLrxL8cbE
#  SECRETKEY: PixamNeEMqTYxJ0lDVg89UDvxJO2BuKbD8eW7CjU
  codes: KRW-BTC,KRW-ETH

gold:
  APIKEY: 5%2F75qRHyFnJO2xACrRNa2fuTmdWmPhiTl2h00EhPfhLTET2KYsiGIT6o5nTPCNW%2FIO1llDBB619wGYitVsyggg%3D%3D

server:
  port: 8089
  servlet:
    context-path: